using System.Reflection;

namespace DataField42.Core.Tests;

/// <summary>
/// The Battlefield Vietnam patch table that gets written into BfVietnam.exe.
/// </summary>
/// <remarks>
/// This table is generated by assemble_patches_bfv.ps1 and then compiled in, so nothing else checks
/// it: a stale or mis-assembled table is written straight into the game's .text and the failure is a
/// crash, not an exception. These assertions decode it the same way the installer writes it.
///
/// VA -> file offset differs per section, which is why the offsets look unrelated:
///   .text  file = VA - 0x400C00      .tls  file = VA - 0x4E6A00
/// </remarks>
public class ClientPatchesTests
{
    private const int TextDelta = 0x400C00;
    private const int TlsDelta = 0x4E6A00;

    private const int MissingMapSite = 0x527CE5;   // CheckSumEvent handler, level search exhausted
    private const int SendtoSite = 0x8D8ED8;       // sendto caller, eax = &sockaddr
    private const int HookMap = 0xE23050;          // cave: build args, disconnect, spawn
    private const int HookStash = 0xE23018;        // cave: copy the server address out of the sockaddr

    private static (int Offset, byte[] Bytes)[] Patches()
    {
        var type = typeof(Bf1942Client).Assembly.GetType("Bf1942ClientPatches")!;
        var field = type.GetField("Patches", BindingFlags.NonPublic | BindingFlags.Static)!;
        return ((int Offset, byte[] Bytes)[])field.GetValue(null)!;
    }

    private static byte[] At(int fileOffset) =>
        Patches().Single(p => p.Offset == fileOffset).Bytes;

    /// <summary>Decodes a call rel32 back to the address it actually reaches.</summary>
    private static int CallTarget(int site, int delta)
    {
        var bytes = At(site - delta);
        Assert.Equal(0xE8, bytes[0]);
        return site + 5 + BitConverter.ToInt32(bytes, 1);
    }

    [Fact]
    public void Missing_map_call_reaches_the_hook()
        => Assert.Equal(HookMap, CallTarget(MissingMapSite, TextDelta));

    [Fact]
    public void Sendto_call_reaches_the_stash_hook()
        => Assert.Equal(HookStash, CallTarget(SendtoSite, TextDelta));

    /// <summary>
    /// Each call must exactly fill what it displaced, or execution resumes mid-instruction.
    /// </summary>
    [Theory]
    [InlineData(MissingMapSite, TextDelta, 6)]  // displaced: mov edx,[edi+0x1f8]
    [InlineData(SendtoSite, TextDelta, 7)]      // displaced: mov edx,[esp+0x10]; mov ecx,[esi+4]
    public void Call_site_is_padded_to_the_displaced_length(int site, int delta, int length)
    {
        var bytes = At(site - delta);
        Assert.Equal(length, bytes.Length);
        Assert.All(bytes.Skip(5), b => Assert.Equal(0x90, b));   // remainder must be nops
    }

    /// <summary>
    /// The hook bodies live in .tls because BFV's .text has no cave big enough. That section is not
    /// executable by default, so the table has to make it so or the first call faults.
    /// </summary>
    [Fact]
    public void Tls_section_is_made_executable()
    {
        var characteristics = BitConverter.ToUInt32(At(0x2EC), 0);
        Assert.Equal(0xE0000040u, characteristics);
        Assert.True((characteristics & 0x20000000) != 0, "IMAGE_SCN_MEM_EXECUTE must be set");
    }

    [Fact]
    public void Hook_bodies_fit_the_tls_cave()
    {
        // 503 zero bytes from VA 0xE23009; the stash occupies 0xE23010..0xE23015.
        const int caveEnd = 0xE23200;
        foreach (var hook in new[] { HookStash, HookMap })
            Assert.InRange(hook + At(hook - TlsDelta).Length, hook, caveEnd);
    }

    [Fact]
    public void Stash_does_not_collide_with_the_hook_that_reads_it()
        => Assert.True(0xE23010 + 6 <= HookStash);

    /// <summary>
    /// The disconnect the hook performs itself must still be in the game's copy too, untouched: the
    /// fall-through path jumps past it, and hooking on top of it is what broke the map name.
    /// </summary>
    [Fact]
    public void Patches_do_not_overlap_the_games_disconnect()
    {
        foreach (var (offset, bytes) in Patches())
        {
            if (offset is 0x2EC) continue;
            var start = offset + TextDelta;
            // 0x527CEB..0x527CF6 is lea/push 0xb/call [edx+0x28] -- must survive
            var overlaps = start < 0x527CF6 && start + bytes.Length > 0x527CEB;
            Assert.False(overlaps, $"patch at 0x{offset:X} overlaps the disconnect sequence");
        }
    }
}
