# Assembles the Battlefield Vietnam hooks and regenerates Bf1942ClientPatches.cs.
#
# Mirrors upstream's assemble_patches.bat, with two differences forced by BFV:
#   * .text has no code cave, so the hook bodies live in the .tls tail and the installer has to flip
#     that section to executable -- a 4-byte header patch with no assembly behind it.
#   * VA -> file offset differs per section, so offsets are computed rather than assumed:
#       .text file = VA - 0x400C00 ; .tls file = VA - 0x4E6A00

$ErrorActionPreference = "Stop"

$nasm = "C:\Users\lucas\AppData\Local\bin\NASM\nasm.exe"
$root = $PSScriptRoot
$out  = Join-Path $root "..\..\DataField42.Core\Models\Bf1942ClientPatches.cs"

$TEXT_DELTA = 0x400C00
$TLS_DELTA  = 0x4E6A00

# name, VA, VA->file delta
$targets = @(
    @{ File = "call hook sendto stash.asm";     Va = 0x8D8ED8;  Delta = $TEXT_DELTA },
    @{ File = "hook function sendto stash.asm"; Va = 0xE23018;  Delta = $TLS_DELTA  },
    @{ File = "call hook missing map.asm";      Va = 0x527CE5;  Delta = $TEXT_DELTA },
    @{ File = "hook function missing map.asm";  Va = 0xE23050;  Delta = $TLS_DELTA  }
)

if (-not (Test-Path $nasm)) { throw "nasm not found at $nasm" }

$entries = @()
foreach ($t in $targets) {
    $src = Join-Path $root $t.File
    $raw = Join-Path $env:TEMP ("bfv_" + [IO.Path]::GetFileNameWithoutExtension($t.File) + ".raw")
    Write-Host "Assembling $($t.File) @ VA 0x$('{0:X}' -f $t.Va) ..."
    # Forward slashes and no trailing backslash: a path ending in \" is read as an escaped quote by
    # the native argument parser and swallows the following argument.
    $inc = ($root -replace '\\', '/') + '/'
    & $nasm -f bin -I $inc $src -o $raw
    if ($LASTEXITCODE -ne 0) { throw "nasm failed on $($t.File)" }

    $bytes = [IO.File]::ReadAllBytes($raw)
    $fileOff = $t.Va - $t.Delta
    Write-Host ("  -> file 0x{0:X}  ({1} bytes)" -f $fileOff, $bytes.Length)
    $entries += @{ Offset = $fileOff; Bytes = $bytes; Note = $t.File }
    Remove-Item $raw -Force
}

# Make .tls executable: Characteristics 0xC0000040 (READ|WRITE|initialised data) -> add MEM_EXECUTE.
# Without this the hook bodies are mapped but not executable and the first call faults.
$entries += @{ Offset = 0x2EC; Bytes = [byte[]](0x40, 0x00, 0x00, 0xE0); Note = ".tls Characteristics -> executable" }

$lines = @(
    "/// <summary>"
    "/// The patches required to hook DataField42 into Battlefield Vietnam."
    "/// </summary>"
    "/// <remarks>"
    "/// This file was generated by assemble_patches_bfv.ps1. Do not edit manually."
    "///"
    "/// Unlike BF1942, BFV has no code cave in .text, so the hook bodies sit in the .tls tail and the"
    "/// last entry flips that section to executable."
    "/// </remarks>"
    "internal static class Bf1942ClientPatches"
    "{"
    "    internal static readonly (int Offset, byte[] Bytes)[] Patches ="
    "    {"
)
foreach ($e in $entries) {
    $hex = ($e.Bytes | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', '
    $lines += "        // $($e.Note)"
    $lines += "        (0x$('{0:X}' -f $e.Offset), new byte[] { $hex }),"
}
$lines += "    };"
$lines += "}"

[IO.File]::WriteAllLines((Resolve-Path $out), $lines, [Text.Encoding]::UTF8)
Write-Host ""
Write-Host "Written $out ($($entries.Count) patches)"
Write-Host ""
Write-Host "NEXT: rebuild and redeploy the client BEFORE running 'DataField42.exe install'." -ForegroundColor Yellow
Write-Host "This table is compiled into DataField42.exe. Regenerating it here changes nothing on disk"  -ForegroundColor Yellow
Write-Host "until the client is republished, and 'install' will happily write the previous table."       -ForegroundColor Yellow
Write-Host "  dotnet publish DataField42\DataField42.csproj -c Release"                                  -ForegroundColor Yellow
Write-Host "  copy the published DataField42.exe into the game folder, then run it with 'install'"       -ForegroundColor Yellow
Write-Host "(Close any open DataField42 window first -- it self-elevates and will hold the file.)"       -ForegroundColor Yellow
