<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>dfvsign</AssemblyName>
    <RootNamespace>DataField42.Sign</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataField42.Core\DataField42.Core.csproj" />
  </ItemGroup>

</Project>
